import { useEffect, useRef, useState, type FormEvent, type ReactNode } from "react";
import { AnimatePresence, motion } from "framer-motion";
import { BRAND } from "../data/content";
import { ModalShell, useModal } from "../lib/ui";
import { escapeHtml, line, sendToTelegram, sendToWhatsApp } from "../lib/telegram";
import { Icon } from "./Icons";

const inputCls = "w-full min-h-[52px] rounded-[4px] border border-white/10 bg-white/[.045] px-4 py-3.5 text-[14px] font-medium text-white placeholder:font-normal placeholder:text-white/28 outline-none transition focus:border-[#d7ff42]/55 focus:bg-white/[.07]";
type Result = "idle" | "sending" | "sent" | "error";
type IntroMode = "problem" | "call";
type ContactMode = "email" | "phone";

function Field({ label, children }: { label: string; children: ReactNode }) { return <label className="block"><span className="mb-2 block font-mono text-[9px] uppercase tracking-[.14em] text-white/45">{label}</span>{children}</label>; }

function ResultView({ result, error, successTitle, successLines, onClose }: { result: Result; error?: string; successTitle: string; successLines: string[]; onClose: () => void }) {
  if (result === "error") return <motion.div initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} className="py-8 text-center"><div className="mx-auto flex h-14 w-14 items-center justify-center rounded-full border border-[#ff946e]/35 text-[#ff946e]"><span className="text-xl">!</span></div><h4 className="mt-5 font-display text-3xl tracking-[-.04em] text-white">Couldn’t send</h4><p className="mx-auto mt-3 max-w-sm text-sm leading-relaxed text-white/48">Please try again, or reach the team at <a className="text-[#d7ff42]" href={`mailto:${BRAND.email}`}>{BRAND.email}</a>.</p><button type="button" onClick={onClose} className="rect-button rect-button-outline mt-7 px-7">Close</button>{error && <p className="mt-3 font-mono text-[9px] text-white/25">{error}</p>}</motion.div>;
  return <motion.div initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} className="py-8 text-center"><div className="mx-auto flex h-14 w-14 items-center justify-center rounded-full bg-[#d7ff42] text-[#07080c]"><Icon name="check" className="h-6 w-6" /></div><h4 className="mt-5 font-display text-3xl tracking-[-.04em] text-white">{successTitle}</h4>{successLines.map((item) => <p key={item} className="mx-auto mt-3 max-w-sm text-sm leading-relaxed text-white/48">{item}</p>)}<button type="button" onClick={onClose} className="rect-button rect-button-acid mt-7 px-7">Done</button></motion.div>;
}

function ModePicker({ mode, onChange }: { mode: IntroMode; onChange: (mode: IntroMode) => void }) {
  const options: Array<[IntroMode, string, string]> = [["problem", "Tell your problem", "Best first move"], ["call", "Book an appointment", "Choose a slot"]];
  return <div className="intro-mode-picker">{options.map(([value, label, detail]) => <button type="button" key={value} onClick={() => onChange(value)} className={`intro-mode ${mode === value ? "intro-mode-active" : ""}`}><span>{label}</span><small>{detail}</small></button>)}</div>;
}

function SubmitButton({ label, loading }: { label: string; loading: boolean }) { return <button type="submit" disabled={loading} className="rect-button rect-button-acid w-full">{loading ? "Sending…" : label}<Icon name="arrow" className="h-4 w-4" /></button>; }
const SLOTS = ["09:00 – 10:00 IST", "11:00 – 12:00 IST", "14:00 – 15:00 IST", "16:00 – 17:00 IST", "18:00 – 19:00 IST"];
const COUNTRY_CODES = ["+91 India", "+1 US / Canada", "+44 UK", "+61 Australia", "+65 Singapore", "+971 UAE", "+234 Nigeria", "+49 Germany", "+81 Japan"];

function FatSelect({ value, onChange, options }: { value: string; onChange: (value: string) => void; options: string[] }) {
  const [open, setOpen] = useState(false);
  const ref = useRef<HTMLDivElement>(null);
  useEffect(() => { if (!open) return; const close = (event: MouseEvent) => { if (ref.current && !ref.current.contains(event.target as Node)) setOpen(false); }; document.addEventListener("mousedown", close); return () => document.removeEventListener("mousedown", close); }, [open]);
  return <div ref={ref} className="relative"><button type="button" onClick={() => setOpen((current) => !current)} className={`${inputCls} flex items-center justify-between text-left`}><span>{value}</span><span className="text-white/35">⌄</span></button><AnimatePresence>{open && <motion.div initial={{ opacity: 0, y: -7 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -7 }} className="glass-strong absolute z-50 mt-2 w-full rounded-[4px] p-1.5 shadow-2xl">{options.map((option) => <button type="button" key={option} onClick={() => { onChange(option); setOpen(false); }} className={`block w-full rounded-[3px] px-3 py-3 text-left text-sm transition ${option === value ? "bg-white/10 text-white" : "text-white/55 hover:bg-white/[.06] hover:text-white"}`}>{option}</button>)}</motion.div>}</AnimatePresence></div>;
}

function ProblemModal({ onClose }: { onClose: () => void }) {
  const [name, setName] = useState(""); const [contact, setContact] = useState(""); const [problem, setProblem] = useState(""); const [result, setResult] = useState<Result>("idle"); const [error, setError] = useState<string>();
  const canSend = name.trim().length > 1 && problem.trim().length > 3;
  async function submit(event: FormEvent) { event.preventDefault(); if (!canSend || result === "sending") return; setResult("sending"); const text = `📩 <b>New problem brief — Aurax</b>\n\n${line("Name:", name.trim())}\n${contact.trim() ? line("Contact:", contact.trim()) + "\n" : ""}<b>What is slowing the business down?</b>\n${escapeHtml(problem.trim())}`; const [telegram, whatsapp] = await Promise.all([sendToTelegram(text), sendToWhatsApp(text)]); setError(telegram.error ?? whatsapp.error); setResult(telegram.ok || whatsapp.ok ? "sent" : "error"); }
  return <ModalShell onClose={onClose} title="Tell us the problem" subtitle="You do not need to know which agent you need. Start with the work that keeps stealing time." accent="#d7ff42"><form onSubmit={submit} className="space-y-5"><Field label="Your name *"><input className={inputCls} placeholder="e.g. Aarav Mehta" value={name} onChange={(event) => setName(event.target.value)} /></Field><Field label="Email or phone (optional)"><input className={inputCls} placeholder="Where should we reach you?" value={contact} onChange={(event) => setContact(event.target.value)} /></Field><Field label="What problem are you facing? *"><textarea className={`${inputCls} min-h-[150px] resize-y`} placeholder="Tell us what repeats, breaks, gets missed, or takes too much time…" value={problem} onChange={(event) => setProblem(event.target.value)} /></Field><SubmitButton label="Send the problem" loading={result === "sending"} /><p className="text-center font-mono text-[9px] uppercase tracking-[.12em] text-white/25">We will come back with the system we would build around it.</p></form>{result === "sent" || result === "error" ? <ResultView result={result} error={error} successTitle="Problem received" successLines={["The brief is with the team. We will respond with a clear next move.", `You can also reach ${BRAND.email}.`]} onClose={onClose} /> : null}</ModalShell>;
}

function IntroModal({ preset, onClose }: { preset: string; onClose: () => void }) {
  const today = new Date().toISOString().split("T")[0]; const [mode, setMode] = useState<IntroMode>(preset === "problem" ? "problem" : "call"); const [name, setName] = useState(""); const [contact, setContact] = useState(""); const [contactMode, setContactMode] = useState<ContactMode>("phone"); const [countryCode, setCountryCode] = useState("+91 India"); const [date, setDate] = useState(""); const [slot, setSlot] = useState(SLOTS[0]); const [details, setDetails] = useState(""); const [result, setResult] = useState<Result>("idle"); const [error, setError] = useState<string>();
  const canSend = name.trim().length > 1 && contact.trim().length > 2 && (mode === "call" ? date.length > 0 : details.trim().length > 3);
  async function submit(event: FormEvent) { event.preventDefault(); if (!canSend || result === "sending") return; setResult("sending"); const label = mode === "call" ? "Appointment request" : "Problem brief"; const contactValue = contactMode === "phone" ? `${countryCode.split(" ")[0]} ${contact.trim()}` : contact.trim(); const text = `📅 <b>${label} — Aurax</b>\n\n${line("Name:", name.trim())}\n${line("Contact:", contactValue)}\n${mode === "call" ? `${line("Date:", date)}\n${line("Time:", slot)}\n` : ""}${details.trim() ? `\n<b>Brief:</b>\n${escapeHtml(details.trim())}` : ""}`; const deliveries = await Promise.all([sendToTelegram(text), sendToWhatsApp(text)]); const ok = deliveries.some((delivery) => delivery.ok); setError(deliveries.find((delivery) => delivery.error)?.error); setResult(ok ? "sent" : "error"); }
  return <ModalShell onClose={onClose} title="Make the first move" subtitle="Choose the quickest way to get the right system in motion." accent="#d7ff42"><ModePicker mode={mode} onChange={(next) => { setMode(next); setResult("idle"); }} />{result === "sent" || result === "error" ? <ResultView result={result} error={error} successTitle={mode === "problem" ? "Problem received" : "Appointment requested"} successLines={["Your request has landed with the Aurax team.", "We will confirm the next step by the contact you shared."]} onClose={onClose} /> : <form onSubmit={submit} className="mt-6 space-y-5"><div className="grid gap-4 sm:grid-cols-2"><Field label="Your name *"><input className={inputCls} placeholder="e.g. Sarah Whitman" value={name} onChange={(event) => setName(event.target.value)} /></Field><Field label="How should we reach you? *"><FatSelect value={contactMode === "email" ? "Email" : "Phone"} onChange={(value) => setContactMode(value === "Phone" ? "phone" : "email")} options={["Email", "Phone"]} /></Field></div>{contactMode === "phone" ? <div className="grid grid-cols-[.72fr_1.28fr] gap-3"><Field label="Country code *"><FatSelect value={countryCode} onChange={setCountryCode} options={COUNTRY_CODES} /></Field><Field label="Phone number *"><input type="tel" className={inputCls} placeholder="98765 43210" value={contact} onChange={(event) => setContact(event.target.value)} /></Field></div> : <Field label="Email address *"><input type="email" className={inputCls} placeholder="you@company.com" value={contact} onChange={(event) => setContact(event.target.value)} /></Field>}{mode === "call" ? <div className="grid gap-4 sm:grid-cols-2"><Field label="Preferred date *"><input type="date" min={today} className={`${inputCls} [color-scheme:dark]`} value={date} onChange={(event) => setDate(event.target.value)} /></Field><Field label="Preferred time"><FatSelect value={slot} onChange={setSlot} options={SLOTS} /></Field></div> : null}<Field label={mode === "problem" ? "What problem are you facing? *" : "What do you want to build? *"}><textarea className={`${inputCls} min-h-[120px] resize-y`} placeholder={mode === "problem" ? "Tell us what repeats, breaks, gets missed, or takes too much time…" : "A short brief — your goals, tools, timeline…"} value={details} onChange={(event) => setDetails(event.target.value)} /></Field><SubmitButton label={mode === "problem" ? "Send the problem" : "Request the appointment"} loading={result === "sending"} /><p className="text-center font-mono text-[9px] uppercase tracking-[.12em] text-white/25">Your details go to the Aurax operations inbox.</p></form>}</ModalShell>;
}

export default function Modals() { const { type, preset, close } = useModal(); return <AnimatePresence>{type === "message" && <ProblemModal key="problem" onClose={close} />}{type === "call" && <IntroModal key="intro" preset={preset} onClose={close} />}</AnimatePresence>; }
