import { useEffect, useState } from "react";
import { AnimatePresence, motion } from "framer-motion";
import { AGENTS, BRAND, NOT_SELLING, REVIEWS, SYSTEMS, WHAT_WE_BUILD } from "../data/content";
import { Reveal, ScrollProgress, useModal } from "../lib/ui";
import { Icon } from "./Icons";
import WorkflowGraph from "./WorkflowGraph";

type Tone = "cyan" | "violet" | "orange" | "lime" | "blue";
type WorkflowNode = { id: string; type: string; title: string; detail: string; tone: Tone };
type WorkflowPreset = { id: string; label: string; kicker: string; title: string; description: string; layout: "branch" | "fanout" | "loop" | "queue" | "escalation" | "linear"; nodes: WorkflowNode[]; yes: WorkflowNode; no: WorkflowNode; branchYes: string; branchNo: string; outcome: WorkflowNode };

const workflows: WorkflowPreset[] = [
  { id: "sales", label: "Sales", layout: "branch", kicker: "01 / REVENUE", title: "Reply to every inbound lead the moment it lands.", description: "The system reads the lead, looks up the company, scores intent, and routes a useful next step before the opportunity goes cold.", nodes: [{ id: "new", type: "TRIGGER", title: "New lead arrives", detail: "Form · Email · WhatsApp", tone: "cyan" }, { id: "lookup", type: "TOOL", title: "Look up the company", detail: "HubSpot · Clearbit", tone: "blue" }, { id: "score", type: "AI STEP", title: "Read & score", detail: "Fit · intent", tone: "violet" }, { id: "worth", type: "DECISION", title: "Worth a call?", detail: "ICP match > 72", tone: "orange" }], yes: { id: "rep", type: "ACTION", title: "Ping the right rep", detail: "Slack DM", tone: "lime" }, no: { id: "reply", type: "ACTION", title: "Send a useful reply", detail: "Pricing · FAQ · deck", tone: "lime" }, branchYes: "YES", branchNo: "NO", outcome: { id: "crm", type: "TOOL", title: "Update the CRM", detail: "HubSpot", tone: "blue" } },
  { id: "finance", label: "Finance", layout: "queue", kicker: "02 / CONTROL", title: "Pay vendors without the data entry.", description: "Invoices are read, matched, checked against policy, and held for human approval only when the risk demands it.", nodes: [{ id: "invoice", type: "TRIGGER", title: "Invoice arrives", detail: "AP inbox · Drive", tone: "cyan" }, { id: "read", type: "AI STEP", title: "Read the invoice", detail: "Vendor · amount · lines", tone: "violet" }, { id: "po", type: "DECISION", title: "Has a PO number?", detail: "YES · NO", tone: "orange" }], yes: { id: "match", type: "TOOL", title: "Match to PO", detail: "PO ledger", tone: "blue" }, no: { id: "review", type: "HUMAN", title: "Send to AP for review", detail: "Slack · one-tap", tone: "orange" }, branchYes: "MATCH", branchNo: "REVIEW", outcome: { id: "approve", type: "HUMAN", title: "Approve & post", detail: "Books · audit trail", tone: "lime" } },
  { id: "marketing", label: "Marketing", layout: "fanout", kicker: "03 / DEMAND", title: "Turn a campaign brief into a week of execution.", description: "A brief becomes channel-ready work, review checkpoints, scheduled distribution, and a clean read on what moved the needle.", nodes: [{ id: "brief", type: "TRIGGER", title: "Brief is approved", detail: "Notion · Slack", tone: "cyan" }, { id: "context", type: "TOOL", title: "Pull brand context", detail: "Assets · voice · ICP", tone: "blue" }, { id: "draft", type: "AI STEP", title: "Draft the campaign", detail: "Hooks · copy · angles", tone: "violet" }, { id: "review", type: "DECISION", title: "Needs review?", detail: "Brand · claim · risk", tone: "orange" }], yes: { id: "publish", type: "ACTION", title: "Publish the variants", detail: "Meta · Google · CRM", tone: "lime" }, no: { id: "edit", type: "HUMAN", title: "Route for edits", detail: "Slack · Figma", tone: "orange" }, branchYes: "CLEAR", branchNo: "EDIT", outcome: { id: "report", type: "TOOL", title: "Report what moved", detail: "Dashboard", tone: "blue" } },
  { id: "followups", label: "Followups", layout: "loop", kicker: "04 / MOMENTUM", title: "Follow up until the answer is clear.", description: "Every open thread gets a respectful next step. Context stays intact, the message changes, and the system knows when to hand the relationship back.", nodes: [{ id: "thread", type: "TRIGGER", title: "Thread goes quiet", detail: "Email · CRM", tone: "cyan" }, { id: "history", type: "TOOL", title: "Read the history", detail: "Messages · stage", tone: "blue" }, { id: "intent", type: "AI STEP", title: "Detect intent", detail: "Timing · objection", tone: "violet" }, { id: "reply", type: "DECISION", title: "Worth another touch?", detail: "Signal · consent", tone: "orange" }], yes: { id: "send", type: "ACTION", title: "Send next step", detail: "Email · WhatsApp", tone: "lime" }, no: { id: "stop", type: "HUMAN", title: "Stop and route", detail: "Rep · owner", tone: "orange" }, branchYes: "YES", branchNo: "STOP", outcome: { id: "log", type: "TOOL", title: "Log the outcome", detail: "CRM timeline", tone: "blue" } },
  { id: "people", label: "People ops", layout: "linear", kicker: "05 / PEOPLE", title: "Keep the people work moving without chasing it.", description: "Requests, approvals, onboarding and handoffs become a visible operating layer that gives every owner the right next action.", nodes: [{ id: "request", type: "TRIGGER", title: "Request arrives", detail: "Form · Slack · HRIS", tone: "cyan" }, { id: "policy", type: "TOOL", title: "Check policy", detail: "Docs · role · region", tone: "blue" }, { id: "draft", type: "AI STEP", title: "Prepare the handoff", detail: "Checklist · owner", tone: "violet" }, { id: "approved", type: "DECISION", title: "Ready to move?", detail: "Missing · blocked", tone: "orange" }], yes: { id: "assign", type: "ACTION", title: "Assign the owner", detail: "Teams · tasks", tone: "lime" }, no: { id: "block", type: "HUMAN", title: "Ask for context", detail: "Owner · manager", tone: "orange" }, branchYes: "READY", branchNo: "BLOCKED", outcome: { id: "audit", type: "TOOL", title: "Close the loop", detail: "HRIS · audit", tone: "blue" } },
  { id: "cx", label: "Customer experience", layout: "escalation", kicker: "06 / RETENTION", title: "Give every customer the answer before they ask twice.", description: "Questions arrive wherever the customer is. Context, sentiment and next-best-action meet in one operating layer.", nodes: [{ id: "question", type: "TRIGGER", title: "Customer writes in", detail: "Chat · Voice · Inbox", tone: "cyan" }, { id: "account", type: "TOOL", title: "Pull account context", detail: "Plan · history · SLA", tone: "blue" }, { id: "intent", type: "AI STEP", title: "Detect intent", detail: "Sentiment · urgency", tone: "violet" }, { id: "human", type: "DECISION", title: "Needs a human?", detail: "Risk · churn", tone: "orange" }], yes: { id: "answer", type: "ACTION", title: "Resolve in context", detail: "Answer · link · action", tone: "lime" }, no: { id: "escalate", type: "HUMAN", title: "Escalate with notes", detail: "Slack · Linear", tone: "orange" }, branchYes: "LOW RISK", branchNo: "ESCALATE", outcome: { id: "learn", type: "TOOL", title: "Learn from the case", detail: "Knowledge base", tone: "blue" } },
];

function Arrow({ className = "h-4 w-4" }: { className?: string }) { return <Icon name="arrow" className={className} />; }

function SpatialNav() {
  const { open } = useModal();
  return <header className="space-nav fixed inset-x-0 top-0 z-50"><div className="mx-auto flex max-w-[1440px] items-center justify-between px-5 py-4 sm:px-8"><a href="#top" className="space-brand flex items-center gap-3"><span className="space-brand-mark">A</span><span className="font-display text-xl tracking-[-.06em] text-white">Aurax<span className="text-[#d7ff42]">.</span></span></a><nav className="hidden items-center gap-8 md:flex">{[["The work", "#work"], ["Systems", "#systems"], ["Operators", "#agents"], ["Proof", "#reviews"], ["Contact", "#contact"]].map(([label, href]) => <a key={label} href={href} className="space-nav-link">{label}</a>)}</nav><button type="button" onClick={() => open("call")} className="rect-button rect-button-light">Book an intro <Arrow className="h-4 w-4" /></button></div></header>;
}

function SignalOrb() {
  return <div className="signal-orb" aria-hidden="true"><div className="signal-orb-grid" /><div className="signal-orb-core"><span>A</span></div><i className="signal-orb-dot dot-one" /><i className="signal-orb-dot dot-two" /><i className="signal-orb-dot dot-three" /><div className="signal-orb-label label-one">LIVE / 24:00:00</div><div className="signal-orb-label label-two">7 ACTIVE AGENTS</div></div>;
}

function CursorSignal() {
  useEffect(() => {
    const root = document.documentElement;
    const move = (event: PointerEvent) => {
      root.style.setProperty("--cursor-x", `${event.clientX}px`);
      root.style.setProperty("--cursor-y", `${event.clientY}px`);
    };
    window.addEventListener("pointermove", move, { passive: true });
    return () => window.removeEventListener("pointermove", move);
  }, []);
  return <div className="cursor-signal" aria-hidden="true"><span /></div>;
}

function Hero() {
  const { open } = useModal();
  return <section id="top" className="new-hero relative overflow-hidden"><div className="hero-grain" /><div className="hero-grid-lines" /><div className="mx-auto grid max-w-[1440px] items-center gap-16 px-5 pb-24 pt-36 sm:px-8 sm:pb-32 sm:pt-48 lg:grid-cols-[1.05fr_.95fr] lg:gap-10"><div className="relative z-10"><Reveal><p className="eyebrow"><span /> AURAX / SYSTEMS STUDIO <b>● ONLINE</b></p></Reveal><Reveal delay={.05}><h1 className="hero-title mt-8">Make the <em>busywork</em> disappear.</h1></Reveal><Reveal delay={.1}><p className="hero-lede mt-8 max-w-xl">We build custom AI systems and infrastructure around the way your business actually moves. No wrappers. No demo theatre. Just the right operators, connected to the work.</p></Reveal><Reveal delay={.16}><div className="mt-9 flex flex-wrap items-center gap-3"><button type="button" onClick={() => open("call")} className="rect-button rect-button-acid">Book a build call <Arrow /></button><button type="button" onClick={() => open("message")} className="rect-button rect-button-line">Tell us the bottleneck <Arrow /></button></div></Reveal><div className="hero-trust mt-16"><span>Built for</span><b>Revenue teams</b><b>Operators</b><b>Founders</b><b>Teams with a bottleneck</b></div></div><Reveal delay={.12} className="relative z-10"><div className="hero-console"><div className="console-top"><span>AURAX / SIGNAL ROOM</span><span className="console-live"><i /> LIVE</span></div><div className="console-main"><div><p className="console-kicker">SYSTEM 03 / PRODUCTION</p><h2>Make the repeatable work disappear.</h2><p>Signals in. Decisions made. Actions owned.</p></div><SignalOrb /></div><div className="console-stats"><span><b>07</b> agents watching</span><span><b>24/7</b> uptime</span><span><b>0</b> handoffs missed</span></div></div></Reveal></div></section>;
}

function DifferenceSection() {
  return <section id="about" className="dark-chapter px-5 py-28 sm:px-8 sm:py-40"><div className="mx-auto max-w-[1200px]"><div className="chapter-head grid gap-8 lg:grid-cols-[.9fr_1.1fr] lg:items-end"><div><p className="eyebrow"><span /> 01 / THE DIFFERENCE</p><h2 className="chapter-title mt-7">Not another <em>AI wrapper.</em></h2></div><p className="chapter-copy max-w-xl">Every business has a bottleneck that steals time or keeps growth just out of reach. We find it, design around it, and build the operating layer that gives your team room to do higher-value work.</p></div><div className="contrast-grid mt-16"><div className="contrast-panel muted"><span className="micro-label">WHAT WE DON'T SELL / 01—04</span>{NOT_SELLING.map((item, index) => <div className="contrast-row" key={item}><span>0{index + 1}</span>{item}</div>)}</div><div className="contrast-panel active"><span className="micro-label">WHAT WE BUILD / 01—04</span>{WHAT_WE_BUILD.map((item, index) => <div className="contrast-row" key={item}><span>0{index + 1}</span>{item}<Icon name="check" className="ml-auto h-4 w-4 text-[#d7ff42]" /></div>)}</div></div></div></section>;
}


function WorkflowSection() {
  const [activeId, setActiveId] = useState("sales");
  const preset = workflows.find((item) => item.id === activeId) ?? workflows[0];
  return <section id="work" className="workflow-chapter relative overflow-hidden"><div className="chapter-stars" /><div className="mx-auto max-w-[1440px] px-5 py-28 sm:px-8 sm:py-40"><div className="chapter-head grid gap-8 lg:grid-cols-[.82fr_1.18fr] lg:items-end"><div><p className="eyebrow"><span /> 03 / IN PRACTICE</p><h2 className="chapter-title mt-7">Built for the way <em>you actually work.</em></h2></div><p className="chapter-copy max-w-xl">Choose the part of the operation that needs a better handoff. Each playbook below is a small view into the kind of custom logic we build and own.</p></div><div className="workflow-tabs mt-12">{workflows.map((item) => <button type="button" key={item.id} onClick={() => setActiveId(item.id)} className={activeId === item.id ? "workflow-tab workflow-tab-active" : "workflow-tab"}>{item.label}</button>)}</div><div className="workflow-story mt-14"><div><p className="console-kicker">{preset.kicker}</p><h3>{preset.title}</h3><p>{preset.description}</p></div><span className="micro-label workflow-count">06 PLAYBOOKS / CUSTOM LOGIC</span></div><Reveal delay={.08} className="mt-12"><WorkflowGraph preset={preset} /></Reveal></div></section>;
}

const SYSTEM_DETAIL_COPY: Record<string, { lede: string; capabilities: string[]; flow: string; outcome: string }> = {
  conversational: { lede: "A context-aware front desk that answers, qualifies, and keeps the conversation moving across every channel.", capabilities: ["Answers recurring questions from your approved knowledge", "Remembers the customer, account, and previous conversation", "Hands off to a human with a complete context packet"], flow: "Question arrives → retrieve context → compose answer → resolve or escalate", outcome: "Fewer repetitive tickets and a faster first response without sacrificing the human handoff." },
  voice: { lede: "A natural voice operator for inbound and outbound calls that can listen, interrupt, qualify, book, and route.", capabilities: ["Handles live calls with interruption and recovery", "Qualifies callers against your rules and calendar", "Transfers high-value or sensitive moments to a person"], flow: "Call connects → listen → qualify → book, route, or hand off", outcome: "More answered calls, fewer missed opportunities, and a calendar that stays in motion after hours." },
  multi: { lede: "A coordinated crew of specialised agents that shares state, owns separate steps, and runs the whole operating loop.", capabilities: ["Splits complex work into owned specialist tasks", "Passes structured context from one agent to the next", "Keeps human approval at the exact risk boundary"], flow: "Request arrives → delegate → execute → verify → close the loop", outcome: "A repeatable operating layer that scales beyond one prompt, one person, or one tool." },
  outbound: { lede: "An always-on outbound system that researches, personalises, follows up, and books qualified conversations.", capabilities: ["Researches and enriches the right accounts", "Personalises outreach by segment and signal", "Stops, retries, or escalates based on response and consent"], flow: "Signal found → research → message → follow-up → meeting booked", outcome: "A healthier pipeline without adding another manual sequence to the team’s week." },
  strategy: { lede: "A system map before implementation: model choice, data flow, ownership, monitoring, and failure paths made explicit.", capabilities: ["Maps the work, systems, and decisions that matter", "Chooses the right model and integration boundary", "Defines guardrails, observability, and escalation before build"], flow: "Constraint → system map → architecture → build plan → production handoff", outcome: "Confidence that the system will be useful in production—not just impressive in a demo." },
  custom: { lede: "A made-to-measure workflow for the exact problem that keeps showing up in your business.", capabilities: ["Starts with your bottleneck instead of a pre-packaged feature", "Fits your tools, data, approvals, and team language", "Ships with a clear owner, monitoring, and next-step path"], flow: "Problem brief → discovery → system design → build → measured handoff", outcome: "A custom operating layer built around the way your business actually moves." },
};

function SystemDetailModal({ system, onClose, onBook }: { system: (typeof SYSTEMS)[number]; onClose: () => void; onBook: () => void }) {
  const detail = SYSTEM_DETAIL_COPY[system.id];
  return <motion.div className="service-modal-backdrop" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} onMouseDown={(event) => { if (event.currentTarget === event.target) onClose(); }}><motion.div role="dialog" aria-modal="true" aria-labelledby="service-detail-title" className="service-modal" initial={{ opacity: 0, y: 20, scale: .98 }} animate={{ opacity: 1, y: 0, scale: 1 }} exit={{ opacity: 0, y: 12, scale: .98 }}><button type="button" className="service-modal-close" onClick={onClose} aria-label="Close service detail">×</button><div className="service-modal-head"><div><span className="paper-eyebrow">SYSTEM DETAIL / {system.tag.toUpperCase()}</span><h2 id="service-detail-title">{system.name}</h2><p>{detail.lede}</p></div><span className="service-modal-index">0{SYSTEMS.findIndex((item) => item.id === system.id) + 1}</span></div><div className="service-modal-grid"><div><span className="service-modal-label">What it handles</span>{detail.capabilities.map((item) => <div key={item} className="service-modal-row"><span>↗</span><p>{item}</p></div>)}</div><div className="service-modal-flow"><span className="service-modal-label">Typical system path</span><div className="service-flow-line">{detail.flow}</div><span className="service-modal-label">What changes</span><p>{detail.outcome}</p></div></div><div className="service-modal-footer"><span>Designed around your stack · owned in production · monitored after launch</span><button type="button" onClick={onBook} className="rect-button rect-button-acid">{system.custom ? "Tell us the problem" : "Book an intro"}<Arrow /></button></div></motion.div></motion.div>;
}

function SystemsSection() {
  const { open } = useModal();
  const [activeId, setActiveId] = useState(SYSTEMS[0].id);
  const [detailId, setDetailId] = useState<string | null>(null);
  const active = SYSTEMS.find((system) => system.id === activeId) ?? SYSTEMS[0];
  const detail = SYSTEMS.find((system) => system.id === detailId);
  return <><section id="systems" className="paper-chapter px-5 py-28 sm:px-8 sm:py-40"><div className="mx-auto max-w-[1200px]"><div className="grid gap-8 lg:grid-cols-[.8fr_1.2fr] lg:items-end"><div><p className="paper-eyebrow">02 / THE OPERATING LAYER</p><h2 className="paper-title mt-6">Start with the constraint.</h2></div><p className="paper-copy max-w-xl">We bring the right mix of agents, tools, orchestration, and guardrails to the work that keeps your business moving.</p></div><div className="system-grid mt-14">{SYSTEMS.map((system, index) => <Reveal key={system.id} delay={index * .03}><button type="button" onClick={() => { setActiveId(system.id); setDetailId(system.id); }} className={`system-card ${activeId === system.id ? "system-card-active" : ""}`}><span className="system-card-no">0{index + 1}</span><span className="system-card-icon" style={{ color: system.accent }}><Icon name={system.icon} className="h-5 w-5" /></span><span className="system-card-tag">{system.tag}</span><h3>{system.name}</h3><p>{system.desc}</p><span className="system-card-link">Open system detail <Arrow className="h-3.5 w-3.5" /></span><span className="system-card-line" style={{ background: system.accent }} /></button></Reveal>)}</div><motion.div key={active.id} initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} className="system-detail mt-5" style={{ borderColor: `${active.accent}66` }}><div><span className="micro-label">SYSTEM DETAIL / {active.tag.toUpperCase()}</span><h3>{active.name}</h3><p>{SYSTEM_DETAIL_COPY[active.id].lede}</p></div><button type="button" onClick={() => setDetailId(active.id)} className="rect-button rect-button-dark">Open full detail<Arrow /></button></motion.div></div></section><AnimatePresence>{detail && <SystemDetailModal key={detail.id} system={detail} onClose={() => setDetailId(null)} onBook={() => { setDetailId(null); detail.custom ? open("message", "custom") : open("call"); }} />}</AnimatePresence></>;
}

function AgentsSection() {
  const { open } = useModal();
  const [active, setActive] = useState(0);
  const agent = AGENTS[active];
  return <section id="agents" className="dark-chapter agents-chapter px-5 py-28 sm:px-8 sm:py-40"><div className="mx-auto max-w-[1200px]"><div className="grid gap-12 lg:grid-cols-[.72fr_1.28fr] lg:items-start"><div><p className="eyebrow"><span /> 04 / AGENTS DOING THE WORK</p><h2 className="chapter-title mt-7">Not demos. <em>Operators.</em></h2><p className="chapter-copy mt-7 max-w-md">Specialised systems for the work that keeps a business moving — shipped with context, guardrails, and a clear owner.</p><button type="button" onClick={() => open("message", "custom")} className="rect-button rect-button-acid mt-9">Build something custom <Arrow /></button></div><div className="agent-console"><div className="agent-tabs">{AGENTS.map((item, index) => <button type="button" key={item.id} onClick={() => setActive(index)} className={active === index ? "agent-tab active" : "agent-tab"}><span>0{index + 1}</span>{item.name.replace(" Automation Agent", "").replace(" Agent", "")}</button>)}</div><div className="agent-console-body"><div><p className="console-kicker">{agent.metric}</p><h3>{agent.name}</h3><p className="agent-tag">{agent.tag}</p></div><span className="agent-icon" style={{ color: agent.accent }}><Icon name={agent.icon} className="h-7 w-7" /></span><p className="agent-description">{agent.desc}</p><div className="agent-ready"><span>System status</span><b><i /> READY TO DEPLOY</b></div></div></div></div></div></section>;
}

function ReviewBands() {
  const featured = REVIEWS.filter((review) => review.featured);
  const scrolling = REVIEWS.filter((review) => !review.featured).slice(0, 12);
  return <section id="reviews" className="proof-chapter px-0 py-28 sm:py-40"><div className="mx-auto max-w-[1200px] px-5 sm:px-8"><p className="paper-eyebrow">05 / PROOF FROM THE OPERATORS</p><div className="proof-heading mt-7"><h2>Rated <em>4.7 / 5</em> by teams worldwide.</h2><p>From Bangalore to Lagos to Toronto — founders and operators running real systems on Aurax.</p></div><div className="featured-reviews mt-14">{featured.map((review) => <article key={review.name} className="featured-review"><div className="featured-stars">★★★★★ <b>{review.rating.toFixed(1)}</b></div><p>“{review.text}”</p><footer>{review.flag} {review.name}<span>{review.role} · {review.company}</span></footer></article>)}</div></div><div className="review-marquee mt-16"><div className="review-track review-track-forward">{[...scrolling, ...scrolling].map((review, index) => <span className="review-card" key={`a-${index}`}><b>★★★★★ {review.rating.toFixed(1)}</b><span>“{review.text}”</span><small>{review.flag} {review.name} · {review.role} · {review.company}</small></span>)}</div></div><div className="review-marquee mt-3"><div className="review-track review-track-reverse">{[...scrolling.slice().reverse(), ...scrolling.slice().reverse()].map((review, index) => <span className="review-card review-card-light" key={`b-${index}`}><b>★★★★★ {review.rating.toFixed(1)}</b><span>“{review.text}”</span><small>{review.flag} {review.name} · {review.role} · {review.company}</small></span>)}</div></div></section>;
}

function ContactSection() {
  const { open } = useModal();
  return <section id="contact" className="contact-chapter px-5 py-24 sm:px-8 sm:py-40"><div className="mx-auto max-w-[1200px]"><div className="contact-panel"><div className="contact-signal" /><p className="eyebrow relative z-10"><span /> 06 / THE FIRST MOVE</p><h2 className="contact-title relative z-10 mt-7">Tell us what keeps <em>stealing time.</em></h2><p className="contact-copy relative z-10 mt-7 max-w-xl">You do not need to know which agent you need. Tell us the bottleneck and we will come back with the system we would build around it.</p><div className="relative z-10 mt-9 flex flex-wrap gap-3"><button type="button" onClick={() => open("call")} className="rect-button rect-button-acid">Schedule a build call <Arrow /></button><button type="button" onClick={() => open("message")} className="rect-button rect-button-outline">Send a message <Arrow /></button></div><div className="contact-meta relative z-10 mt-16"><span><small>Operations inbox</small>Telegram + email routing</span><span><small>Email</small><a href={`mailto:${BRAND.email}`}>{BRAND.email}</a></span><span><small>Response</small>Within a few hours</span></div></div></div></section>;
}

export default function PremiumHome() {
  return <><ScrollProgress /><CursorSignal /><SpatialNav /><main><Hero /><DifferenceSection /><WorkflowSection /><SystemsSection /><AgentsSection /><ReviewBands /><ContactSection /></main><footer className="site-footer"><div className="mx-auto flex max-w-[1200px] flex-col gap-4 px-5 py-8 sm:flex-row sm:items-center sm:justify-between sm:px-8"><a href="#top" className="font-display text-xl tracking-[-.05em] text-white">Aurax<span className="text-[#d7ff42]">.</span></a><span className="micro-label">AI AGENT SYSTEMS / INFRASTRUCTURE / BUILT FOR THE REAL WORLD</span><a href="https://instagram.com/aurax.systems" target="_blank" rel="noreferrer" className="micro-label hover:text-[#d7ff42]">@aurax.systems</a></div></footer></>;
}
