import { useMemo, useState } from "react";
import { motion } from "framer-motion";
import { AGENTS, BRAND, NOT_SELLING, REVIEWS, SYSTEMS, WHAT_WE_BUILD } from "../data/content";
import { Reveal, ScrollProgress, useModal } from "../lib/ui";
import { Icon } from "./Icons";
import Chatbot from "./Chatbot";

type Tone = "cyan" | "violet" | "orange" | "lime" | "blue";
type WorkflowNode = { id: string; type: string; title: string; detail: string; x: number; y: number; tone: Tone };
type WorkflowPreset = { id: string; label: string; kicker: string; title: string; description: string; nodes: WorkflowNode[]; paths: string[]; branchLabels?: Array<{ text: string; x: number; y: number }> };

const workflowPresets: WorkflowPreset[] = [
  {
    id: "sales", label: "Sales", kicker: "SALES", title: "Reply to every inbound lead the moment it lands", description: "Leads arrive from forms, inboxes, WhatsApp. The agent reads each one, looks up the company, decides fit, then pings the right rep or sends a useful auto-reply. CRM stays current.",
    nodes: [
      { id: "new", type: "TRIGGER", title: "New lead arrives", detail: "Form · Email · WhatsApp", x: 2, y: 42, tone: "cyan" }, { id: "lookup", type: "TOOL", title: "Look up the company", detail: "HubSpot · Clearbit", x: 18, y: 42, tone: "blue" }, { id: "score", type: "AI STEP", title: "Read & score", detail: "Fit · intent", x: 34, y: 42, tone: "violet" }, { id: "worth", type: "DECISION", title: "Worth a call?", detail: "ICP match > 72", x: 50, y: 42, tone: "orange" }, { id: "rep", type: "ACTION", title: "Ping the right rep", detail: "Slack DM", x: 67, y: 18, tone: "lime" }, { id: "reply", type: "ACTION", title: "Send a useful reply", detail: "Pricing · FAQ · deck", x: 67, y: 66, tone: "lime" }, { id: "crm", type: "TOOL", title: "Update the CRM", detail: "HubSpot", x: 86, y: 42, tone: "blue" },
    ], paths: ["M15 50 C16 50 17 50 18 50", "M31 50 C32 50 33 50 34 50", "M47 50 C48 50 49 50 50 50", "M63 50 C65 50 65 26 67 26", "M63 50 C65 50 65 74 67 74", "M82 26 C84 26 84 50 86 50", "M82 74 C84 74 84 50 86 50"], branchLabels: [{ text: "YES", x: 64, y: 31 }, { text: "NO", x: 64, y: 68 }] },
  {
    id: "finance", label: "Finance", kicker: "FINANCE", title: "Pay vendors without the data entry", description: "Invoices arrive as PDFs in AP. The agent reads each one, matches the PO, and drafts the entry in your books. Anything over a threshold pauses for one-tap approval in Slack.",
    nodes: [
      { id: "invoice", type: "TRIGGER", title: "Invoice arrives", detail: "AP inbox · Drive", x: 2, y: 42, tone: "cyan" }, { id: "read", type: "AI STEP", title: "Read the invoice", detail: "Vendor · amount · lines", x: 18, y: 42, tone: "violet" }, { id: "po", type: "DECISION", title: "Has a PO number?", detail: "YES · NO", x: 34, y: 42, tone: "orange" }, { id: "match", type: "TOOL", title: "Match to PO", detail: "PO ledger", x: 51, y: 18, tone: "blue" }, { id: "review", type: "HUMAN", title: "Send to AP for review", detail: "Slack · one-tap", x: 51, y: 66, tone: "orange" }, { id: "threshold", type: "DECISION", title: "Amount over ₹1L?", detail: "Risk · policy", x: 68, y: 42, tone: "orange" }, { id: "approve", type: "HUMAN", title: "Wait for approver", detail: "Slack · approve", x: 85, y: 42, tone: "lime" },
    ], paths: ["M15 50 C16 50 17 50 18 50", "M31 50 C32 50 33 50 34 50", "M47 50 C49 50 49 26 51 26", "M47 50 C49 50 49 74 51 74", "M66 26 C68 26 68 50 68 50", "M66 74 C68 74 68 50 68 50", "M84 50 C84.5 50 84.5 50 85 50"], branchLabels: [{ text: "YES", x: 48, y: 31 }, { text: "NO", x: 48, y: 68 }] },
  {
    id: "marketing", label: "Marketing", kicker: "MARKETING", title: "Turn a campaign brief into a week of execution", description: "A brief enters once. The system turns it into channel-ready variations, routes approvals, schedules the work, and reports what moved the needle.",
    nodes: [
      { id: "brief", type: "TRIGGER", title: "Brief is approved", detail: "Notion · Slack", x: 2, y: 42, tone: "cyan" }, { id: "context", type: "TOOL", title: "Pull brand context", detail: "Assets · voice · ICP", x: 18, y: 42, tone: "blue" }, { id: "draft", type: "AI STEP", title: "Draft the campaign", detail: "Hooks · copy · angles", x: 34, y: 42, tone: "violet" }, { id: "review", type: "HUMAN", title: "Needs review?", detail: "Brand · claim · risk", x: 50, y: 42, tone: "orange" }, { id: "publish", type: "ACTION", title: "Publish the variants", detail: "Meta · Google · CRM", x: 67, y: 18, tone: "lime" }, { id: "edit", type: "ACTION", title: "Route for edits", detail: "Slack · Figma", x: 67, y: 66, tone: "orange" }, { id: "report", type: "TOOL", title: "Report what moved", detail: "Dashboard", x: 86, y: 42, tone: "blue" },
    ], paths: ["M15 50 C16 50 17 50 18 50", "M31 50 C32 50 33 50 34 50", "M47 50 C48 50 49 50 50 50", "M63 50 C65 50 65 26 67 26", "M63 50 C65 50 65 74 67 74", "M82 26 C84 26 84 50 86 50", "M82 74 C84 74 84 50 86 50"], branchLabels: [{ text: "CLEAR", x: 64, y: 31 }, { text: "EDIT", x: 64, y: 68 }] },
  {
    id: "followups", label: "Followups", kicker: "FOLLOWUPS", title: "Follow up until the answer is clear", description: "Every open thread gets a respectful next step. The agent remembers context, changes the message, and stops when a human should take over.",
    nodes: [
      { id: "thread", type: "TRIGGER", title: "Thread goes quiet", detail: "Email · CRM", x: 2, y: 42, tone: "cyan" }, { id: "history", type: "TOOL", title: "Read the history", detail: "Messages · stage", x: 18, y: 42, tone: "blue" }, { id: "intent", type: "AI STEP", title: "Detect intent", detail: "Timing · objection", x: 34, y: 42, tone: "violet" }, { id: "reply", type: "DECISION", title: "Worth another touch?", detail: "Signal · consent", x: 50, y: 42, tone: "orange" }, { id: "send", type: "ACTION", title: "Send next step", detail: "Email · WhatsApp", x: 67, y: 18, tone: "lime" }, { id: "stop", type: "HUMAN", title: "Stop and route", detail: "Rep · owner", x: 67, y: 66, tone: "orange" }, { id: "log", type: "TOOL", title: "Log the outcome", detail: "CRM timeline", x: 86, y: 42, tone: "blue" },
    ], paths: ["M15 50 C16 50 17 50 18 50", "M31 50 C32 50 33 50 34 50", "M47 50 C48 50 49 50 50 50", "M63 50 C65 50 65 26 67 26", "M63 50 C65 50 65 74 67 74", "M82 26 C84 26 84 50 86 50", "M82 74 C84 74 84 50 86 50"], branchLabels: [{ text: "YES", x: 64, y: 31 }, { text: "NO", x: 64, y: 68 }] },
  {
    id: "people", label: "People ops", kicker: "PEOPLE OPS", title: "Keep the people work moving without chasing it", description: "Requests, approvals, onboarding and handoffs become a visible operating layer that gives every owner the right next action.",
    nodes: [
      { id: "request", type: "TRIGGER", title: "Request arrives", detail: "Form · Slack · HRIS", x: 2, y: 42, tone: "cyan" }, { id: "policy", type: "TOOL", title: "Check policy", detail: "Docs · role · region", x: 18, y: 42, tone: "blue" }, { id: "draft", type: "AI STEP", title: "Prepare the handoff", detail: "Checklist · owner", x: 34, y: 42, tone: "violet" }, { id: "approved", type: "DECISION", title: "Ready to move?", detail: "Missing · blocked", x: 50, y: 42, tone: "orange" }, { id: "assign", type: "ACTION", title: "Assign the owner", detail: "Teams · tasks", x: 67, y: 18, tone: "lime" }, { id: "block", type: "HUMAN", title: "Ask for context", detail: "Owner · manager", x: 67, y: 66, tone: "orange" }, { id: "audit", type: "TOOL", title: "Close the loop", detail: "HRIS · audit", x: 86, y: 42, tone: "blue" },
    ], paths: ["M15 50 C16 50 17 50 18 50", "M31 50 C32 50 33 50 34 50", "M47 50 C48 50 49 50 50 50", "M63 50 C65 50 65 26 67 26", "M63 50 C65 50 65 74 67 74", "M82 26 C84 26 84 50 86 50", "M82 74 C84 74 84 50 86 50"], branchLabels: [{ text: "READY", x: 64, y: 31 }, { text: "BLOCKED", x: 64, y: 68 }] },
  {
    id: "cx", label: "Customer experience", kicker: "CUSTOMER EXPERIENCE", title: "Give every customer the answer before they ask twice", description: "Questions arrive wherever the customer is. Context, sentiment and next-best-action meet in one operating layer, with a human ready when it matters.",
    nodes: [
      { id: "question", type: "TRIGGER", title: "Customer writes in", detail: "Chat · Voice · Inbox", x: 2, y: 42, tone: "cyan" }, { id: "account", type: "TOOL", title: "Pull account context", detail: "Plan · history · SLA", x: 18, y: 42, tone: "blue" }, { id: "intent", type: "AI STEP", title: "Detect intent", detail: "Sentiment · urgency", x: 34, y: 42, tone: "violet" }, { id: "human", type: "DECISION", title: "Needs a human?", detail: "Risk · churn", x: 50, y: 42, tone: "orange" }, { id: "answer", type: "ACTION", title: "Resolve in context", detail: "Answer · link · action", x: 67, y: 18, tone: "lime" }, { id: "escalate", type: "HUMAN", title: "Escalate with notes", detail: "Slack · Linear", x: 67, y: 66, tone: "orange" }, { id: "learn", type: "TOOL", title: "Learn from the case", detail: "Knowledge base", x: 86, y: 42, tone: "blue" },
    ], paths: ["M15 50 C16 50 17 50 18 50", "M31 50 C32 50 33 50 34 50", "M47 50 C48 50 49 50 50 50", "M63 50 C65 50 65 26 67 26", "M63 50 C65 50 65 74 67 74", "M82 26 C84 26 84 50 86 50", "M82 74 C84 74 84 50 86 50"], branchLabels: [{ text: "LOW RISK", x: 64, y: 31 }, { text: "ESCALATE", x: 64, y: 68 }] },
];

const tones: Record<Tone, { line: string; wash: string }> = {
  cyan: { line: "#82e9e2", wash: "rgba(87,217,208,.12)" }, blue: { line: "#8799ff", wash: "rgba(113,135,255,.12)" }, violet: { line: "#c9b5ff", wash: "rgba(179,155,255,.12)" }, orange: { line: "#ff9c79", wash: "rgba(255,148,110,.12)" }, lime: { line: "#d7ff42", wash: "rgba(215,255,66,.11)" },
};

function Arrow({ className = "h-4 w-4" }: { className?: string }) { return <Icon name="arrow" className={className} />; }

function SpatialNav() {
  const { open } = useModal();
  return <header className="space-nav fixed inset-x-0 top-0 z-50"><div className="mx-auto flex max-w-[1440px] items-center justify-between px-5 py-5 sm:px-8"><a href="#top" className="space-brand flex items-center gap-3"><span className="space-brand-mark">A</span><span className="font-display text-xl tracking-[-.06em] text-white">Aurax<span className="text-[#d7ff42]">.</span></span></a><nav className="hidden items-center gap-8 md:flex">{[["The work", "#work"], ["About", "#about"], ["Resources", "#resources"], ["Contact", "#contact"]].map(([label, href]) => <a key={label} href={href} className="space-nav-link">{label}{label === "The work" || label === "Resources" ? <span className="ml-1 text-white/30">⌄</span> : null}</a>)}</nav><button type="button" onClick={() => open("call")} className="angled-button angled-button-light">Book an intro <Arrow className="h-4 w-4" /></button></div></header>;
}

function MovingGlobe() {
  return <div className="moving-globe" aria-label="Aurax globe system visualization"><span className="globe-halo" /><span className="globe-orbit globe-orbit-a" /><span className="globe-orbit globe-orbit-b" /><div className="globe-sphere"><svg viewBox="0 0 240 240" aria-hidden="true"><circle cx="120" cy="120" r="87" fill="none" stroke="rgba(215,255,66,.5)" strokeWidth="1" /><ellipse cx="120" cy="120" rx="87" ry="29" fill="none" stroke="rgba(255,255,255,.28)" strokeWidth="1" /><ellipse cx="120" cy="120" rx="87" ry="56" fill="none" stroke="rgba(255,255,255,.2)" strokeWidth="1" /><ellipse cx="120" cy="120" rx="27" ry="87" fill="none" stroke="rgba(255,255,255,.22)" strokeWidth="1" /><ellipse cx="120" cy="120" rx="56" ry="87" fill="none" stroke="rgba(255,255,255,.18)" strokeWidth="1" /><path d="M42 103 C75 84 164 84 198 103" fill="none" stroke="rgba(135,153,255,.65)" strokeWidth="1" /><path d="M42 139 C77 157 164 157 198 139" fill="none" stroke="rgba(255,148,110,.55)" strokeWidth="1" /></svg><span className="globe-pin globe-pin-a" /><span className="globe-pin globe-pin-b" /><span className="globe-pin globe-pin-c" /></div><div className="globe-caption"><span>EARTH / MOVING DATA</span><span>07.24° N</span></div></div>;
}

function Hero() {
  const { open } = useModal();
  return <section className="spatial-hero relative overflow-hidden" id="top"><div className="starfield" /><div className="hero-orbit hero-orbit-one" /><div className="hero-orbit hero-orbit-two" /><div className="mx-auto grid max-w-[1440px] items-center gap-12 px-5 pb-24 pt-40 sm:px-8 sm:pb-32 sm:pt-52 lg:grid-cols-[1fr_.86fr] lg:gap-24"><div className="relative z-10"><Reveal><p className="space-kicker"><span className="space-kicker-line" />03 <span>—</span> IN PRACTICE</p></Reveal><Reveal delay={.06}><h1 className="spatial-title mt-9">Built for the way <em>you actually work.</em></h1></Reveal><Reveal delay={.12}><p className="spatial-copy mt-8 max-w-xl">We don't sell usual end-to-end workflows. We build AI systems and infrastructure that fit the way your business actually moves.</p></Reveal><Reveal delay={.18}><div className="mt-9 flex flex-wrap items-center gap-5"><button type="button" onClick={() => open("call")} className="angled-button angled-button-acid">Book a build call <Arrow className="h-4 w-4" /></button><button type="button" onClick={() => open("message")} className="ghost-link">Describe the problem <Arrow className="h-4 w-4" /></button></div></Reveal></div><Reveal delay={.16} className="relative z-10"><div className="hero-signal-card"><div className="hero-signal-top"><span className="font-mono text-[9px] uppercase tracking-[.2em] text-white/35">Aurax / signal room</span><span className="signal-live"><span /> LIVE</span></div><div className="hero-signal-copy"><p className="font-mono text-[9px] uppercase tracking-[.2em] text-[#d7ff42]">SYSTEM 03 / PRODUCTION</p><h2>Make the repeatable work disappear.</h2><p>Signals in. Decisions made. Actions owned.</p></div><MovingGlobe /><div className="hero-signal-foot"><span>7 agents watching</span><span>24/7 uptime</span><span>0 handoffs missed</span></div></div></Reveal></div><div className="mx-auto flex max-w-[1440px] items-center gap-3 border-t border-white/10 px-5 py-4 sm:px-8"><span className="font-mono text-[9px] uppercase tracking-[.18em] text-white/35">Built for</span>{["Revenue teams", "Operators", "Founders", "Teams with a bottleneck"].map((item) => <span key={item} className="chip-label">{item}</span>)}</div></section>;
}

function WorkflowDiagram({ preset }: { preset: WorkflowPreset }) {
  const [active, setActive] = useState(2);
  const activeNode = preset.nodes[active % preset.nodes.length];
  return <div className="workflow-shell"><div className="workflow-shell-head"><span className="font-mono text-[9px] uppercase tracking-[.22em] text-white/40">— EXAMPLE WORKFLOW</span><span className="workflow-run-state"><span className={activeNode ? "run-dot" : ""} /> {activeNode ? "RUNNING — HOVER TO RE-RUN" : "IDLE — HOVER TO RUN"}</span></div><div className="workflow-canvas-wrap"><div className="workflow-canvas"><div className="workflow-stars" /><svg className="workflow-svg" viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true">{preset.paths.map((path, index) => <motion.path key={`${preset.id}-${index}`} d={path} fill="none" stroke={index === 5 || index === 6 ? "#d7ff42" : "rgba(255,255,255,.48)"} strokeWidth=".24" strokeDasharray={active === index ? "1.8 1.2" : "0"} animate={active === index ? { strokeDashoffset: [0, -12] } : { strokeDashoffset: 0 }} transition={{ duration: 1.3, repeat: active === index ? Infinity : 0, ease: "linear" }} />)}{preset.branchLabels?.map((label) => <text key={label.text} x={label.x} y={label.y} fill="rgba(255,255,255,.42)" fontSize="1.7" letterSpacing=".25">{label.text}</text>)}</svg>{preset.nodes.map((node, index) => { const tone = tones[node.tone]; return <motion.button key={node.id} type="button" className={`workflow-card ${active === index ? "workflow-card-active" : ""}`} style={{ left: `${node.x}%`, top: `${node.y}%`, borderColor: `${tone.line}70`, background: `linear-gradient(145deg, ${tone.wash}, rgba(10,11,14,.9))`, boxShadow: active === index ? `0 0 34px -14px ${tone.line}` : undefined }} onMouseEnter={() => setActive(index)} onFocus={() => setActive(index)} onClick={() => setActive(index)} animate={active === index ? { y: [0, -3, 0] } : { y: 0 }} transition={{ duration: 2.2, repeat: active === index ? Infinity : 0, ease: "easeInOut" }}><span className="workflow-card-type" style={{ color: tone.line }}>{node.type}</span><strong>{node.title}</strong><small>{node.detail}</small><i style={{ background: tone.line }} /></motion.button>; })}</div></div><div className="workflow-shell-foot"><div className="workflow-legend"><span><i className="legend-cyan" /> Trigger</span><span><i className="legend-violet" /> Intelligence</span><span><i className="legend-lime" /> Action</span></div><span className="font-mono text-[9px] uppercase tracking-[.16em] text-white/32">Active node / {activeNode.title}</span></div></div>;
}

function WorkflowSection() {
  const [activeId, setActiveId] = useState("sales");
  const preset = workflowPresets.find((item) => item.id === activeId) ?? workflowPresets[0];
  return <section id="work" className="workflow-section relative overflow-hidden"><div className="starfield starfield-deep" /><div className="mx-auto max-w-[1440px] px-5 py-28 sm:px-8 sm:py-40"><div className="flex flex-col gap-10 lg:flex-row lg:items-end lg:justify-between"><div><Reveal><p className="space-kicker"><span className="space-kicker-line" />03 <span>—</span> IN PRACTICE</p></Reveal><Reveal delay={.05}><h2 className="spatial-subtitle mt-8">Built for the way <em>you actually work.</em></h2></Reveal></div><Reveal delay={.1} className="max-w-xl"><p className="spatial-copy">Your systems should feel like an extension of your team, not a second job. Choose the part of the operation that needs a better handoff.</p></Reveal></div><div className="workflow-tabs mt-12">{workflowPresets.map((item) => <button type="button" key={item.id} onClick={() => setActiveId(item.id)} className={`workflow-tab ${activeId === item.id ? "workflow-tab-active" : ""}`}>{item.label}</button>)}</div><Reveal delay={.12}><div className="mt-14 grid gap-8 lg:grid-cols-[.78fr_1.22fr] lg:items-end"><div><p className="font-mono text-[10px] uppercase tracking-[.22em] text-white/45">{preset.kicker}</p><h3 className="mt-6 max-w-3xl font-sans text-[clamp(2rem,4vw,4.5rem)] font-semibold leading-[.95] tracking-[-.06em] text-white">{preset.title}</h3><p className="mt-7 max-w-xl text-base leading-relaxed text-white/48">{preset.description}</p></div><div className="hidden justify-end lg:flex"><span className="font-mono text-[9px] uppercase tracking-[.16em] text-white/32">{workflowPresets.length} playbooks / custom logic</span></div></div></Reveal><Reveal delay={.16} className="mt-12"><WorkflowDiagram preset={preset} /></Reveal></div></section>;
}

function DifferenceSection() {
  return <section id="about" className="ink-section px-5 py-28 sm:px-8 sm:py-40"><div className="mx-auto max-w-[1200px]"><div className="grid gap-12 lg:grid-cols-[.72fr_1.28fr] lg:items-end"><div><Reveal><p className="space-kicker"><span className="space-kicker-line" />01 <span>—</span> THE DIFFERENCE</p></Reveal><Reveal delay={.05}><h2 className="spatial-subtitle mt-8">Not another <em>AI wrapper.</em></h2></Reveal></div><Reveal delay={.1}><p className="spatial-copy max-w-xl">Every business has a bottleneck that steals time or keeps growth just out of reach. We find it, design around it, and build the operating layer that gives your team room to do higher-value work.</p></Reveal></div><div className="mt-16 grid gap-4 md:grid-cols-2"><Reveal className="h-full"><div className="difference-panel difference-muted"><span className="panel-label">WHAT WE DON'T SELL / 01—04</span>{NOT_SELLING.map((item, index) => <div className="difference-row" key={item}><span>0{index + 1}</span>{item}</div>)}</div></Reveal><Reveal delay={.1} className="h-full"><div className="difference-panel difference-highlight"><span className="panel-label">WHAT WE BUILD / 01—04</span>{WHAT_WE_BUILD.map((item, index) => <div className="difference-row" key={item}><span>0{index + 1}</span>{item}<Icon name="check" className="ml-auto h-4 w-4 text-[#d7ff42]" /></div>)}</div></Reveal></div></div></section>;
}

function SystemGrid() {
  const { open } = useModal();
  return <section id="resources" className="paper-section px-5 py-28 sm:px-8 sm:py-40"><div className="mx-auto max-w-[1200px]"><div className="grid gap-10 lg:grid-cols-[.7fr_1.3fr] lg:items-end"><div><p className="paper-kicker">The operating layer</p><h2 className="paper-title mt-7">Start with the constraint.</h2></div><p className="paper-copy max-w-xl">We bring the right mix of agents, tools, orchestration, and guardrails to the work that keeps your business moving.</p></div><div className="mt-14 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{SYSTEMS.map((system, index) => <Reveal key={system.id} delay={index * .03}><button type="button" onClick={system.custom ? () => open("message", "custom") : undefined} className="system-card group text-left"><span className="system-number">0{index + 1}</span><span className="system-icon" style={{ color: system.accent }}><Icon name={system.icon} className="h-5 w-5" /></span><span className="mt-12 block font-mono text-[9px] uppercase tracking-[.18em] text-black/35">{system.tag}</span><h3 className="mt-3 font-display text-3xl tracking-[-.05em] text-black/85">{system.name}</h3><p className="mt-4 text-sm leading-relaxed text-black/52">{system.desc}</p><span className="system-link">{system.custom ? "Describe your system" : "Explore the system"}<Arrow className="h-3.5 w-3.5 transition group-hover:translate-x-1" /></span><span className="system-accent" style={{ background: system.accent }} /></button></Reveal>)}</div></div></section>;
}

function AgentSection() {
  const { open } = useModal();
  const [active, setActive] = useState(0);
  return <section className="ink-section px-5 py-28 sm:px-8 sm:py-40"><div className="mx-auto max-w-[1200px]"><div className="grid gap-12 lg:grid-cols-[.72fr_1.28fr] lg:items-start"><div><p className="space-kicker"><span className="space-kicker-line" />04 <span>—</span> AGENTS DOING THE WORK</p><h2 className="spatial-subtitle mt-8">Not demos. <em>Operators.</em></h2><p className="spatial-copy mt-7 max-w-md">Specialised systems for the work that keeps a business moving — shipped with the context and guardrails to operate in production.</p><button type="button" onClick={() => open("message", "custom")} className="angled-button angled-button-acid mt-9">Build something custom <Arrow className="h-4 w-4" /></button></div><div className="agent-room"><div className="agent-room-tabs">{AGENTS.map((agent, index) => <button type="button" key={agent.id} onClick={() => setActive(index)} className={active === index ? "agent-room-tab active" : "agent-room-tab"}><span>{String(index + 1).padStart(2, "0")}</span>{agent.name.replace(" Automation Agent", "").replace(" Agent", "")}</button>)}</div><div className="agent-room-body"><div><p className="font-mono text-[9px] uppercase tracking-[.18em] text-[#d7ff42]">{AGENTS[active].metric}</p><h3 className="mt-5 font-display text-4xl tracking-[-.06em] text-white sm:text-6xl">{AGENTS[active].name}</h3><p className="mt-3 font-mono text-[10px] uppercase tracking-[.15em] text-white/35">{AGENTS[active].tag}</p></div><span className="agent-room-icon" style={{ color: AGENTS[active].accent }}><Icon name={AGENTS[active].icon} className="h-7 w-7" /></span><p className="mt-16 max-w-xl text-base leading-relaxed text-white/53">{AGENTS[active].desc}</p><div className="mt-10 flex items-center justify-between border-t border-white/10 pt-5"><span className="font-mono text-[9px] uppercase tracking-[.15em] text-white/30">System status</span><span className="signal-live"><span /> READY TO DEPLOY</span></div></div></div></div></div></section>;
}

function ReviewBands() {
  const reviews = useMemo(() => REVIEWS.map((review) => `${review.text} — ${review.name} · ★★★★★ ${review.rating.toFixed(1)} / 5`), []);
  const rowA = [...reviews, ...reviews, ...reviews];
  const rowB = [...reviews.slice().reverse(), ...reviews.slice().reverse(), ...reviews.slice().reverse()];
  return <section id="reviews" className="review-section overflow-hidden px-0 py-28 sm:py-40"><div className="mx-auto max-w-[1200px] px-5 sm:px-8"><p className="space-kicker"><span className="space-kicker-line" />05 <span>—</span> PROOF FROM THE OPERATORS</p><h2 className="spatial-subtitle mt-8 max-w-3xl">Rated <em>4.7 / 5</em> by teams worldwide.</h2><p className="spatial-copy mt-7 max-w-xl">From Bangalore to Lagos to Toronto — founders and operators running real systems on Aurax.</p></div><div className="review-marquee mt-16"><div className="review-track review-track-forward">{rowA.map((review, index) => <span className="review-pill" key={`a-${index}`}>“{review}”</span>)}</div></div><div className="review-marquee mt-3"><div className="review-track review-track-reverse">{rowB.map((review, index) => <span className="review-pill review-pill-light" key={`b-${index}`}>“{review}”</span>)}</div></div></section>;
}

function ContactSection() {
  const { open } = useModal();
  return <section id="contact" className="contact-section px-5 py-24 sm:px-8 sm:py-40"><div className="mx-auto max-w-[1200px]"><div className="contact-room"><div className="contact-glow" /><p className="space-kicker relative z-10"><span className="space-kicker-line" />07 <span>—</span> THE FIRST MOVE</p><h2 className="contact-title relative z-10 mt-8">Tell us what keeps <em>stealing time.</em></h2><p className="relative z-10 mt-8 max-w-xl text-base leading-relaxed text-white/52">You don't need to know what type of agent you need. Tell us the problem. In under 48 hours, we'll come back with the system we'd build around it.</p><div className="relative z-10 mt-9 flex flex-wrap gap-4"><button type="button" onClick={() => open("call")} className="angled-button angled-button-acid">Schedule a build call <Arrow className="h-4 w-4" /></button><button type="button" onClick={() => open("message")} className="angled-button angled-button-outline">Send a message <Arrow className="h-4 w-4" /></button></div><div className="relative z-10 mt-16 grid gap-5 border-t border-white/10 pt-5 text-sm sm:grid-cols-3"><div><span className="contact-label">Operations inbox</span><span className="contact-value">Telegram + email routing</span></div><div><span className="contact-label">Email</span><a className="contact-value" href={`mailto:${BRAND.email}`}>{BRAND.email}</a></div><div><span className="contact-label">Response</span><span className="contact-value">Within a few hours</span></div></div></div></div></section>;
}

export default function PremiumHome() {
  return <><ScrollProgress /><SpatialNav /><main><Hero /><DifferenceSection /><WorkflowSection /><SystemGrid /><AgentSection /><ReviewBands /><ContactSection /></main><footer className="space-footer"><div className="mx-auto flex max-w-[1200px] flex-col gap-5 px-5 py-8 sm:flex-row sm:items-center sm:justify-between sm:px-8"><a href="#top" className="font-display text-xl tracking-[-.05em] text-white">Aurax<span className="text-[#d7ff42]">.</span></a><span className="font-mono text-[9px] uppercase tracking-[.16em] text-white/35">AI agent systems & infrastructure / built for web & mobile</span><a href="https://instagram.com/aurax.systems" target="_blank" rel="noreferrer" className="font-mono text-[9px] uppercase tracking-[.16em] text-white/45 hover:text-[#d7ff42]">@aurax.systems</a></div></footer><Chatbot /></>;
}
